sudo: required
services:
  - docker
before_install:
  - docker-compose up --build
before_script: 
  - docker network ls
script: 
  - docker exec WebServer npm run test
after_script: 
  - docker-compose down
env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME