language: node_js
node_js:
  - "10"
cache:
  yarn: true
  npm: true
os:
  - linux
  - osx
  - windows
install:
  - npm install
script:
  - npm start -verbose
  - npm test
services:
  - mongodb
# Travis has built-in yarn 1.3.2 atm.
# We install 1.10.1 to be able to run bins from root node_modules
# in child projects (without having to specify them as dev deps in each project)
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
notifications:
    slack: $SLACK
    if: branch = dev OR master
    on_success: always
    on_failure: always
    on_pull_requests: false
env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME
