sudo: required
services:
  - docker
  - mongodb

before_install:
  - docker build -t msrober3/mongo-seed -f ./mongo-seed/Dockerfile.dev ./mongo-seed
  - docker build -t msrober3/badging-system -f ./WebServer/Dockerfile.dev ./WebServer

before_script:
  - docker-compose up --build -d

script: 
  - docker run msrober3/badging-system npm test -- --coverage
  
after_script:
  - docker-compose down

env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME