language: node_js
node_js:
  - "12.13"
os:
  - linux
before_install:
  - npm install -g grunt-cli
install:
  - npm install -g
script:
  - npm start -verbose &
  - ps
# services:
#   - mongodb
notifications:
    slack: $SLACK
    if: branch = Task-#52
    on_success: always
    on_failure: false
    on_pull_requests: false
    email: false
env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME
