sudo: required
services:
  - docker

before_install:
  - docker build -t msrober3/mongo -f ./mongo/Dockerfile.dev ./mongo
  - docker build -t msrober3/mongo-seed -f ./mongo-seed/Dockerfile.dev ./mongo-seed
  - docker build -t msrober3/badging-system -f ./WebServer/Dockerfile.dev ./WebServer

script: 
  - docker run msrober3/badging-system npm test -- --coverage

env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME