language: node_js
node_js:
  - "12"
os:
  - linux
before_script:
  - npm start &
install:
  - npm install -g
  - npm install -g mocha
  - npm install --save-dev chai
  - npm update
script:
  - sleep 15
  - npm test
after_script:
  - ps
services:
  - mongodb
notifications:
    slack: $SLACK
    if: branch = dev OR master
    on_success: always
    on_failure: always
    on_pull_requests: false
    email: false
env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME
