language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm install
script:
  - npm start
  - make test
services:
  - mongodb
notifications:
    slack: $SLACK
    if: branch = dev OR master
    on_success: always
    on_failure: always
    on_pull_requests: false
env:
  - ENV=$ENVIRONMENT
  - PORT=$PORT
  - HOST=$HOST
  - DBNAME=$DBNAME
