sudo: required
services:
  - docker
before_install:
  - chmod +x build.sh
before_install:
  - docker-compose up -d --build
before_script: 
  - docker ps
script: 
  - docker exec WebServer npm run test
after_script: 
  - docker-compose down
env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME