sudo: required
services:
  - docker
  - mongodb
  
before_install:
  - docker build -t msrober3/mongo-seed -f ./mongo-seed/Dockerfile.dev ./mongo-seed

script: 
  - docker run msrober3/badging-system npm test -- --coverage

env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME