sudo: required
services:
  - docker
  - mongodb

before_install:
  - docker build -t msrober3/badging-system -f ./WebServer/Dockerfile.dev ./WebServer

before_script:
  - ls

script: 
  - docker run msrober3/badging-system npm test -- --coverage

env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME