language: node_js
node_js:
  - "10"
os:
  - linux
  - osx
  - windows
install:
  - npm install -g
before_deploy:
  - eval "$(ssh-agent -s)"
  - ssh-agent -k
script:
  - npm start -verbose
services:
  - mongodb
notifications:
    slack: $SLACK
    if: branch = dev OR master
    on_success: always
    on_failure: always
    on_pull_requests: false
env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME
