version: '3'
services:
    api:
        volumes:
            - /var/www/node_modules
            - ./WebServer:/var/www
        container_name: WebServer
        environment:
            - ENV=DEV
            - PORT=8080
            - HOST=mongodb://mongo:27017/
            - DBNAME=badging-system
        build:
            context: ./WebServer
            dockerfile: Dockerfile.dev
        links:
            - mongo
        depends_on: 
            - mongo
        expose: 
            - 8080
        networks:
            - app-network
    client:
        container_name: client
        volumes:
            - /var/www/node_modules
            - ./FrontEnd:/var/www
        build: 
            context: ./FrontEnd
            dockerfile: Dockerfile.dev
        networks:
            - app-network
        expose:
            - 3000
    mongo:
        image: mongo
        restart: always
        networks:
            - app-network
    mongo-seed:
        build:
            context: ./mongo-seed
            dockerfile: Dockerfile.dev
        links:
            - mongo
        networks:
            - app-network
    nginx:
        depends_on: 
            - api
            - client
        restart: always
        build: 
            context: ./Nginx
            dockerfile: Dockerfile.dev
        ports: 
            - '4000:80'
        networks:
            - app-network
    swagger:
        image: swaggerapi/swagger-ui
        container_name: "swagger"
        volumes:
            - ./WebServer/server/swagger-doc.json:/var/www/swagger-doc.json
        environment:
            - SWAGGER_JSON=/var/www/swagger-doc.json
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
        