FROM mongo

COPY ./data /

# CMD mongoimport --host mongo --db badging-system --collection teams --type json --file /teams.json --jsonArray

CMD mongoimport --host mongo --db badging-system --collection users --type json --file /users.json --jsonArray
