language: node_js
node_js:
  - "12"
os:
  - linux
cache:
  directories:
    - node_modules
install:
  - npm install -g
  - npm install -g mocha
  - npm install --save-dev chai
  - npm update
script:
  - npm test
services:
  - mongodb
notifications:
    slack:             $SLACK
    if:                branch = dev OR master
    on_success:        always
    on_failure:        always
    on_pull_requests:  false
    email:             false
env:
  - ENV=$ENVIRONMENT PORT=$PORT HOST=$HOST DBNAME=$DBNAME
